#!/bin/sh

# Copyright (c) 2000-2026, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#
# Version
#

VERSION='1.5.0'

#
# Program name
#

_0='lockss-downloader'

#
# Constants
#

DEFAULT_GIT_BRANCH='master'
DEFAULT_GIT_PROJECT='https://github.com/lockss/lockss-installer'

#
# Fatal
# $1: optional message
#
Fatal()
{
  if [ -n "${1}" ] ; then
    echo "${_0}: error: ${1}" >&2
  fi
  exit 1
}

#
# Graceful
#
Graceful()
{
  exit 0
}

#
# Check_Root
#
Check_Root()
{
  if [ "$(id -u)" = '0' ] ; then
    Fatal 'cannot be run as root'
  fi
}


#
# Create_Download_Dir
#
Create_Download_Dir()
{
  if [ -d "${DOWNLOAD_DIR}" ] ; then
    return
  fi
  if [ -e "${DOWNLOAD_DIR}" ] ; then
    Fatal "${DOWNLOAD_DIR} already exists but is not a directory"
  fi
  mkdir -p "${DOWNLOAD_DIR}" || Fatal "could not create ${DOWNLOAD_DIR}"
}

#
# Display_Summary
#
Display_Summary()
{
  if [ "${QUIET}" != 'true' ] ; then
    case "${GIT_BRANCH}${GIT_COMMIT}${GIT_TAG}" in
      "${GIT_BRANCH}") _s="branch: ${GIT_BRANCH}" ;;
      "${GIT_COMMIT}") _s="commit: ${GIT_COMMIT}" ;;
      "${GIT_TAG}") _s="tag: ${GIT_TAG}" ;;
      *) Fatal 'invalid Git state' ;; # shouldn't happen
    esac
    echo "https://github.com/${GIT_PROJECT} downloaded into ${DOWNLOAD_DIR} (${_s})"
  fi
}

#
# Download_From_Github
#
Download_From_Github()
{
  case "${GIT_BRANCH}${GIT_COMMIT}${GIT_TAG}" in
    "${GIT_BRANCH}") _url="https://github.com/${GIT_PROJECT}/archive/refs/heads/${GIT_BRANCH}" ;;
    "${GIT_COMMIT}") _url="https://github.com/${GIT_PROJECT}/archive/${GIT_COMMIT}" ;;
    "${GIT_TAG}") _url="https://github.com/${GIT_PROJECT}/archive/refs/tags/${GIT_TAG}" ;;
    *) Fatal 'unknown Git reference' ;; # shouldn't happen
  esac
  case "${ARCHIVER}" in
    gtar|tar) _url="${_url}.tar.gz" ;;
    *) Fatal "unknown archiver: ${ARCHIVER}" ;; # shouldn't happen
  esac
  ( case "${DOWNLOADER}" in
      curl) curl -sSfL "${_url}" ;;
      wget) wget -qO- "${_url}" ;;
      http) http -qd "${_url}" ;;
      *) Fatal "unknown downloader: ${DOWNLOADER}" ;; # shouldn't happen
    esac \
      | case "${ARCHIVER}" in
          gtar|tar) "$ARCHIVER" xzf - --directory="${DOWNLOAD_DIR}" --strip-components=1 ;;
          *) Fatal "unknown archiver: ${ARCHIVER}" ;; # shouldn't happen ;;
        esac ) || Fatal "could not download and extract ${_url}"
}

#
# Make_Command_Line_Parser
#
Make_Command_Line_Parser()
{
  setup REST alt:TRUE help:Print_Help -- 'Usage:' \
    "  ${_0} [--download-dir=DIR] [--branch=BRA|--commit=COM|--tag=TAG] [--curl|--wget] [--quiet] [PROJECT]" \
    "  ${_0} --version" \
    "  ${_0} --help" \
    '' \
    "PROJECT argument format (default: ${DEFAULT_GIT_PROJECT})" \
    '  https://github.com/<x>/<y>' \
    '  https://github.com/<x>/<y>.git' \
    '  git@github.com:<x>/<y>' \
    '  git@github.com:<x>/<y>.git' \
    '  <x>/<y> (GitHub implied)'
  msg -- '' 'Directory options'
  param :'Set_Download_Dir "${OPTARG}"' var:DIR --download-dir -d -- 'Download into DIR (default: $HOME/<y> with <y> from PROJECT)'
  msg -- '' "Git options (default: ${DEFAULT_GIT_BRANCH} branch of PROJECT)"
  param :'Set_Git_Branch "${OPTARG}"' var:BRA --branch --git-branch -b -- 'Use the Git branch BRA (deprecated: --git-branch)'
  param :'Set_Git_Commit "${OPTARG}"' var:COM --commit --git-commit -c -- 'Use the Git commit COM (deprecated: --git-commit)'
  param :'Set_Git_Tag "${OPTARG}"' var:TAG --tag --git-tag -t -- 'Use the Git tag TAG (deprecated: --git-tag)'
  msg -- '' 'Downloader options (default: Curl then Wget)'
  flag CURL --curl -C -- 'Force the use of Curl'
  flag WGET --wget -W -- 'Force the use of Wget'
  msg -- '' 'Other options'
  disp :Print_Help --help -h -- 'Display this help message and exit'
  flag QUIET --quiet -q -- 'Produce no output unless an error occurs'
  disp :'echo $VERSION' --version -- 'Display the version and exit'
}

#
# Parse_Command_Line_2
# Must be called with "$@"
#
Parse_Command_Line_2()
{
  case $# in
    0) Set_Git_Project "${DEFAULT_GIT_PROJECT}" ;;
    1) Set_Git_Project "${1}" ;;
    *) shift ; "too many arguments: $@" ;;
  esac

  case "${CURL}${WGET}" in
    ''|"${CURL}"|"${WGET}") ;;
    *) Fatal 'at most one of --curl, --wget can be specified' ;;
  esac

  case "${GIT_BRANCH}${GIT_COMMIT}${GIT_TAG}" in
    '') GIT_BRANCH="${DEFAULT_GIT_BRANCH}" ;;
    "${GIT_BRANCH}"|"${GIT_COMMIT}"|"${GIT_TAG}") ;;
    *) Fatal 'at most one of --branch, --commit, --tag can be specified' ;;
  esac

  # Must be before DOWNLOAD_DIR section
  if [ -z "${GIT_PROJECT}" ] ; then
    Set_Git_Project "${DEFAULT_GIT_PROJECT}"
  fi

  if [ -z "${DOWNLOAD_DIR}" ] ; then
    Set_Download_Dir "${HOME}/$(basename "${GIT_PROJECT}")"
  fi

}

#
# Set_Archiver
#
Set_Archiver()
{
  if [ "$(uname -s)" = 'Darwin' ] && command -v gtar > /dev/null ; then
    ARCHIVER='gtar'
  elif command -v tar > /dev/null ; then
    ARCHIVER='tar'
  fi
  if [ -z "${ARCHIVER}" ] ; then
    Fatal 'no tar (or gtar) on the PATH'
  fi
}

#
# Set_Download_Dir
# $1: directory path
#
Set_Download_Dir()
{
  if [ -z "${1}" ] ; then
    Fatal '--download-dir: empty directory path'
  fi
  if [ -z "${DOWNLOAD_DIR}" ] ; then
    DOWNLOAD_DIR="${1}"
  elif [ "${1}" != "${DOWNLOAD_DIR}" ] ; then
    Fatal "--download-dir: ${1} conflicts with ${DOWNLOAD_DIR}"
  fi
}

#
# Set_Downloader
# $1: executable
#
Set_Downloader()
{
  case "${CURL}${WGET}" in
    '')
      for _d in curl wget ; do
        if command -v "${_d}" > /dev/null ; then
          DOWNLOADER="${_d}"
          break
        fi
      done
      if [ -z "${DOWNLOADER}" ] ; then
        Fatal 'at least one of curl, wget must be on the PATH'
      fi
      ;;
    "${CURL}")
      if command -v curl > /dev/null ; then
        DOWNLOADER='curl'
      else
        Fatal '--curl: curl must be on the PATH'
      fi
      ;;
    "${WGET}")
      if command -v wget > /dev/null ; then
        DOWNLOADER='wget'
      else
        Fatal '--wget: wget must be on the PATH'
      fi
      ;;
    *)
      Fatal 'invalid downloader'
      ;; # shouldn't happen
  esac
}

#
# Set_Git_Branch
# $1: branch name
#
Set_Git_Branch()
{
  if [ -z "${1}" ] ; then
    Fatal '--branch: empty branch name'
  fi
  if [ -z "${GIT_BRANCH}" ] ; then
    GIT_BRANCH="${1}"
  elif [ "${1}" != "${GIT_BRANCH}" ] ; then
    Fatal "--branch: ${1} conflicts with ${GIT_BRANCH}"
  fi
}

#
# Set_Git_Commit
# $1: commit name
#
Set_Git_Commit()
{
  if [ -z "${1}" ] ; then
    Fatal '--commit: empty commit name'
  fi
  if [ -z "${GIT_COMMIT}" ] ; then
    GIT_COMMIT="${1}"
  elif [ "${1}" != "${GIT_COMMIT}" ] ; then
    Fatal "--commit: ${1} conflicts with ${GIT_COMMIT}"
  fi
}

#
# Set_Git_Project
# $1: project reference (foo/bar, https://github.com/foo/bar, https://github.com/foo/bar.git, git@github.com:foo/bar, git@github.com:foo/bar.git)
#
Set_Git_Project()
{
  if [ -z "${1}" ] ; then
    Fatal 'empty project reference'
  fi
  case "${1}" in
    https://github.com/*/*) _proj="${1%.git}" ; _proj="${_proj#https://github.com/}" ;;
    git@github.com:*/*) _proj="${1%.git}" ; _proj="${_proj#git@github.com:}" ;;
    */*) _proj="${1}" ;;
    *) Fatal "invalid project reference: ${1}" ;;
  esac
  if [ "${_proj%/*}/${_proj#*/}" != "${_proj}" ] ; then
    Fatal "invalid project reference: ${1}"
  fi
  if [ -z "${GIT_PROJECT}" ] ; then
    GIT_PROJECT="${_proj}"
  elif [ "${_proj}" != "${GIT_PROJECT}" ] ; then
    Fatal "${_proj} conflicts with ${GIT_PROJECT}"
  fi
}

#
# Set_Git_Tag
# $1: tag name
#
Set_Git_Tag()
{
  if [ -z "${1}" ] ; then
    Fatal '--tag: empty tag name'
  fi
  if [ -z "${GIT_TAG}" ] ; then
    GIT_TAG="${1}"
  elif [ "${1}" != "${GIT_TAG}" ] ; then
    Fatal "--tag: ${1} conflicts with ${GIT_TAG}"
  fi
}

#
# Output of: lib/getoptions/gengetoptions library -i 2
#

#  #####   #####   ####   ###  #    #  
#   #   #  #      #    #   #   #    #  
#   #   #  #      #        #   ##   #  
#   #   #  #      #        #   # #  #  
#   ####   ####   #        #   #  # #  
#   #   #  #      #  ###   #   #   ##  
#   #   #  #      #    #   #   #    #  
#   #   #  #      #   ##   #   #    #  
#  #####   #####   ### #  ###  #    #  
# [getoptions] License: Creative Commons Zero v1.0 Universal
# https://github.com/ko1nksm/getoptions (v3.3.2)
getoptions() {
  _error="" _on=1 _no="" _export="" _plus="" _mode="" _alt="" _rest="" _def=""
  _flags="" _nflags="" _opts="" _help="" _abbr="" _cmds="" _init=@empty IFS=" "
  [ $# -lt 2 ] && set -- "${1:?No parser definition}" -
  [ "$2" = - ] && _def=getoptions_parse

  i="					"
  while eval "_${#i}() { echo \"$i\$@\"; }" && [ "$i" ]; do i=${i#?}; done

  quote() {
    q="$2'" r=""
    while [ "$q" ]; do r="$r${q%%\'*}'\''" && q=${q#*\'}; done
    q="'${r%????}'" && q=${q#\'\'} && q=${q%\'\'}
    eval "$1=\${q:-\"''\"}"
  }
  code() {
    [ "${1#:}" = "$1" ] && c=3 || c=4
    eval "[ ! \${$c:+x} ] || $2 \"\$$c\""
  }
  sw() { sw="$sw${sw:+|}$1"; }
  kv() { eval "${2-}${1%%:*}=\${1#*:}"; }
  loop() { [ $# -gt 1 ] && [ "$2" != -- ]; }

  invoke() { eval '"_$@"'; }
  prehook() { invoke "$@"; }
  for i in setup flag param option disp msg; do
    eval "$i() { prehook $i \"\$@\"; }"
  done

  args() {
    on=$_on no=$_no export=$_export init=$_init _hasarg=$1 && shift
    while loop "$@" && shift; do
      case $1 in
        -?) [ "$_hasarg" ] && _opts="$_opts${1#-}" || _flags="$_flags${1#-}" ;;
        +?) _plus=1 _nflags="$_nflags${1#+}" ;;
        [!-+]*) kv "$1"
      esac
    done
  }
  defvar() {
    case $init in
      @none) : ;;
      @export) code "$1" _0 "export $1" ;;
      @empty) code "$1" _0 "${export:+export }$1=''" ;;
      @unset) code "$1" _0 "unset $1 ||:" "unset OPTARG ||:; ${1#:}" ;;
      *)
        case $init in @*) eval "init=\"=\${${init#@}}\""; esac
        case $init in [!=]*) _0 "$init"; return 0; esac
        quote init "${init#=}"
        code "$1" _0 "${export:+export }$1=$init" "OPTARG=$init; ${1#:}"
    esac
  }
  _setup() {
    [ "${1#-}" ] && _rest=$1
    while loop "$@" && shift; do kv "$1" _; done
  }
  _flag() { args "" "$@"; defvar "$@"; }
  _param() { args 1 "$@"; defvar "$@"; }
  _option() { args 1 "$@"; defvar "$@"; }
  _disp() { args "" "$@"; }
  _msg() { args "" _ "$@"; }

  cmd() { _mode=@ _cmds="$_cmds${_cmds:+|}'$1'"; }
  "$@"
  cmd() { :; }
  _0 "${_rest:?}=''"

  _0 "${_def:-$2}() {"
  _1 'OPTIND=$(($#+1))'
  _1 "while OPTARG= && [ \"\${$_rest}\" != x ] && [ \$# -gt 0 ]; do"
  [ "$_abbr" ] && getoptions_abbr "$@"

  args() {
    sw="" validate="" pattern="" counter="" on=$_on no=$_no export=$_export
    while loop "$@" && shift; do
      case $1 in
        --\{no-\}*) i=${1#--?no-?}; sw "'--$i'|'--no-$i'" ;;
        --with\{out\}-*) i=${1#--*-}; sw "'--with-$i'|'--without-$i'" ;;
        [-+]? | --*) sw "'$1'" ;;
        *) kv "$1"
      esac
    done
    quote on "$on"
    quote no "$no"
  }
  setup() { :; }
  _flag() {
    args "$@"
    [ "$counter" ] && on=1 no=-1 v="\$((\${$1:-0}+\$OPTARG))" || v=""
    _3 "$sw)"
    _4 '[ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break'
    _4 "eval '[ \${OPTARG+x} ] &&:' && OPTARG=$on || OPTARG=$no"
    valid "$1" "${v:-\$OPTARG}"
    _4 ";;"
  }
  _param() {
    args "$@"
    _3 "$sw)"
    _4 '[ $# -le 1 ] && set "required" "$1" && break'
    _4 'OPTARG=$2'
    valid "$1" '$OPTARG'
    _4 "shift ;;"
  }
  _option() {
    args "$@"
    _3 "$sw)"
    _4 'set -- "$1" "$@"'
    _4 '[ ${OPTARG+x} ] && {'
    _5 'case $1 in --no-*|--without-*) set "noarg" "${1%%\=*}"; break; esac'
    _5 '[ "${OPTARG:-}" ] && { shift; OPTARG=$2; } ||' "OPTARG=$on"
    _4 "} || OPTARG=$no"
    valid "$1" '$OPTARG'
    _4 "shift ;;"
  }
  valid() {
    set -- "$validate" "$pattern" "$1" "$2"
    [ "$1" ] && _4 "$1 || { set -- ${1%% *}:\$? \"\$1\" $1; break; }"
    [ "$2" ] && {
      _4 "case \$OPTARG in $2) ;;"
      _5 '*) set "pattern:'"$2"'" "$1"; break'
      _4 "esac"
    }
    code "$3" _4 "${export:+export }$3=\"$4\"" "${3#:}"
  }
  _disp() {
    args "$@"
    _3 "$sw)"
    code "$1" _4 "echo \"\${$1}\"" "${1#:}"
    _4 "exit 0 ;;"
  }
  _msg() { :; }

  [ "$_alt" ] && _2 'case $1 in -[!-]?*) set -- "-$@"; esac'
  _2 'case $1 in'
  _wa() { _4 "eval 'set -- $1' \${1+'\"\$@\"'}"; }
  _op() {
    _3 "$1) OPTARG=\$1; shift"
    _wa '"${OPTARG%"${OPTARG#??}"}" '"$2"'"${OPTARG#??}"'
    _4 "${4:-}$3"
  }
  _3 '--?*=*) OPTARG=$1; shift'
  _wa '"${OPTARG%%\=*}" "${OPTARG#*\=}"'
  _4 ";;"
  _3 "--no-*|--without-*) unset OPTARG ;;"
  [ "$_alt" ] || {
    [ "$_opts" ] && _op "-[$_opts]?*" "" ";;"
    [ ! "$_flags" ] || _op "-[$_flags]?*" - "OPTARG= ;;" \
      'case $2 in --*) set -- "$1" unknown "$2" && '"$_rest=x; esac;"
  }
  [ "$_plus" ] && {
    [ "$_nflags" ] && _op "+[$_nflags]?*" + "unset OPTARG ;;"
    _3 "+*) unset OPTARG ;;"
  }
  _2 "esac"
  _2 'case $1 in'
  "$@"
  rest() {
    _4 'while [ $# -gt 0 ]; do'
    _5 "$_rest=\"\${$_rest}" '\"\${$(($OPTIND-$#))}\""'
    _5 "shift"
    _4 "done"
    _4 "break ;;"
  }
  _3 "--)"
  [ "$_mode" = @ ] || _4 "shift"
  rest
  _3 "[-${_plus:++}]?*)" 'set "unknown" "$1"; break ;;'
  _3 "*)"
  case $_mode in
    @)
      _4 "case \$1 in ${_cmds:-*}) ;;"
      _5 '*) set "notcmd" "$1"; break'
      _4 "esac"
      rest ;;
    +) rest ;;
    *) _4 "$_rest=\"\${$_rest}" '\"\${$(($OPTIND-$#))}\""'
  esac
  _2 "esac"
  _2 "shift"
  _1 "done"
  _1 '[ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }'
  _1 'case $1 in'
  _2 'unknown) set "Unrecognized option: $2" "$@" ;;'
  _2 'noarg) set "Does not allow an argument: $2" "$@" ;;'
  _2 'required) set "Requires an argument: $2" "$@" ;;'
  _2 'pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;'
  _2 'notcmd) set "Not a command: $2" "$@" ;;'
  _2 '*) set "Validation error ($1): $2" "$@"'
  _1 "esac"
  [ "$_error" ] && _1 "$_error" '"$@" >&2 || exit $?'
  _1 'echo "$1" >&2'
  _1 "exit 1"
  _0 "}"

  [ "$_help" ] && eval "shift 2; getoptions_help $1 $_help" ${3+'"$@"'}
  [ "$_def" ] && _0 "eval $_def \${1+'\"\$@\"'}; eval set -- \"\${$_rest}\""
  _0 "# Do not execute" # exit 1
}
# [getoptions_abbr] License: Creative Commons Zero v1.0 Universal
# https://github.com/ko1nksm/getoptions (v3.3.2)
getoptions_abbr() {
  abbr() {
    _3 "case '$1' in"
    _4 '"$1") OPTARG=; break ;;'
    _4 '$1*) OPTARG="$OPTARG '"$1"'"'
    _3 "esac"
  }
  args() {
    abbr=1
    shift
    [ $# -gt 0 ] || return 0
    for i in "$@"; do
      case $i in
        --) break ;;
        [!-+]*) eval "${i%%:*}=\${i#*:}"
      esac
    done
    [ "$abbr" ] || return 0

    for i in "$@"; do
      case $i in
        --) break ;;
        --\{no-\}*) abbr "--${i#--\{no-\}}"; abbr "--no-${i#--\{no-\}}" ;;
        --*) abbr "$i"
      esac
    done
  }
  setup() { :; }
  for i in flag param option disp; do
    eval "_$i()" '{ args "$@"; }'
  done
  msg() { :; }
  _2 'set -- "${1%%\=*}" "${1#*\=}" "$@"'
  [ "$_alt" ] && _2 'case $1 in -[!-]?*) set -- "-$@"; esac'
  _2 'while [ ${#1} -gt 2 ]; do'
  _3 'case $1 in (*[!a-zA-Z0-9_-]*) break; esac'
  "$@"
  _3 "break"
  _2 "done"
  _2 'case ${OPTARG# } in'
  _3 "*\ *)"
  _4 'eval "set -- $OPTARG $1 $OPTARG"'
  _4 'OPTIND=$((($#+1)/2)) OPTARG=$1; shift'
  _4 'while [ $# -gt "$OPTIND" ]; do OPTARG="$OPTARG, $1"; shift; done'
  _4 'set "Ambiguous option: $1 (could be $OPTARG)" ambiguous "$@"'
  [ "$_error" ] && _4 "$_error" '"$@" >&2 || exit $?'
  _4 'echo "$1" >&2'
  _4 "exit 1 ;;"
  _3 "?*)"
  _4 '[ "$2" = "$3" ] || OPTARG="$OPTARG=$2"'
  _4 "shift 3; eval 'set -- \"\${OPTARG# }\"' \${1+'\"\$@\"'}; OPTARG= ;;"
  _3 "*) shift 2"
  _2 "esac"
}
# [getoptions_help] License: Creative Commons Zero v1.0 Universal
# https://github.com/ko1nksm/getoptions (v3.3.2)
getoptions_help() {
  _width="30,12" _plus="" _leading="  "

  pad() { p=$2; while [ ${#p} -lt "$3" ]; do p="$p "; done; eval "$1=\$p"; }
  kv() { eval "${2-}${1%%:*}=\${1#*:}"; }
  sw() { pad sw "$sw${sw:+, }" "$1"; sw="$sw$2"; }

  args() {
    _type=$1 var=${2%% *} sw="" label="" hidden="" && shift 2
    while [ $# -gt 0 ] && i=$1 && shift && [ "$i" != -- ]; do
      case $i in
        --*) sw $((${_plus:+4}+4)) "$i" ;;
        -?) sw 0 "$i" ;;
        +?) [ ! "$_plus" ] || sw 4 "$i" ;;
        *) [ "$_type" = setup ] && kv "$i" _; kv "$i"
      esac
    done
    [ "$hidden" ] && return 0 || len=${_width%,*}

    [ "$label" ] || case $_type in
      setup | msg) label="" len=0 ;;
      flag | disp) label="$sw " ;;
      param) label="$sw $var " ;;
      option) label="${sw}[=$var] "
    esac
    [ "$_type" = cmd ] && label=${label:-$var } len=${_width#*,}
    pad label "${label:+$_leading}$label" "$len"
    [ ${#label} -le "$len" ] && [ $# -gt 0 ] && label="$label$1" && shift
    echo "$label"
    pad label "" "$len"
    [ $# -gt 0 ] || return 0
    for i in "$@"; do echo "$label$i"; done
  }

  for i in setup flag param option disp "msg -" cmd; do
    eval "${i% *}() { args $i \"\$@\"; }"
  done

  echo "$2() {"
  echo "cat<<'GETOPTIONSHERE'"
  "$@"
  echo "GETOPTIONSHERE"
  echo "}"
}
#  #####  #    #  #####   
#  #      #    #   #   #  
#  #      ##   #   #   #  
#  #      # #  #   #   #  
#  ####   #  # #   #   #  
#  #      #   ##   #   #  
#  #      #    #   #   #  
#  #      #    #   #   #  
#  #####  #    #  #####   

################################################################################
# Main
################################################################################

#
# Variables
#

ARCHIVER=''
DOWNLOAD_DIR=''
DOWNLOADER=''
GIT_BRANCH=''
GIT_COMMIT=''
GIT_PROJECT=''
GIT_TAG=''
REST=''

#
# Main
#

eval "$(getoptions Make_Command_Line_Parser Parse_Command_Line)"
Parse_Command_Line "$@"
eval "set -- $REST"
Parse_Command_Line_2 "$@"
Check_Root
Set_Downloader
Set_Archiver
Create_Download_Dir
Download_From_Github
Display_Summary
Graceful
